DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS test CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS targets CASCADE;
DROP TABLE IF EXISTS parents CASCADE;
DROP TABLE IF EXISTS children CASCADE;
DROP TABLE IF EXISTS surveys CASCADE;
DROP SEQUENCE IF EXISTS test_sequence CASCADE;